services:

  nest-backend:
    container_name: nest-service
    build:
      context: ./nest-service
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    restart: unless-stopped
    environment:
      JWT_SECRET: yourSecretKey
