# render.yaml — Infrastructure as Code

services:
  # - type: web
  #   name: frontend
  #   env: node
  #   plan: free
  #   buildCommand: |
  #     cd helperly-app
  #     npm install
  #     npm run build
  #   startCommand: |
  #     cd helperly-app
  #     npm run start
  #   envVars:
  #     - key: NEXT_PUBLIC_NEST_SERVICE
  #       value: https://nest-backend-service.onrender.com
  #     - key: NODE_ENV
  #       value: production

  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: |
      cd nest-service
      npm install
      npx prisma generate
      npm run build
    startCommand: |
      cd nest-service
      npm run start
    envVars:
      - key: JWT_SECRET
        value: yourSecretKey
      - key: NODE_ENV
        value: production
