export const mockSolutions = [
  {
    id: "1",
    name: "Production Line Optimization",
    description: "Streamlines manufacturing processes to reduce waste and increase output",
    kind: "Process Improvement",
    location: "Manufacturing Plant A",
    mode: "Continuous",
    status: "Active",
    defaultSectionId: "sec-001",
    defaultSectionName: "Assembly Line",
    defaultSubSectionId: "sub-001",
    defaultSubSectionName: "Final Assembly",
    defaultEventId: "evt-001",
    defaultEventName: "Quality Check",
    content: "Detailed implementation steps for the production line optimization solution.",
    problem: "High defect rate and slow production speed on assembly line",
    title: "Assembly Line Efficiency Improvement",
    what: "Redesign of assembly line workflow and quality control processes",
    why: "To reduce defects by 30% and increase production speed by 25%",
    where: "Manufacturing Plant A, Assembly Line Section",
    when: "Implemented during Q3 2023",
    how: "Using lean manufacturing principles and automated quality control systems",
    email: "production.manager@example.com",
    solutionDetails: {
      title: "Assembly Line Optimization",
      description: "Comprehensive approach to streamline assembly processes",
      rootCause: "Inefficient workstation layout and manual quality checks",
      countermeasure: "Redesigned workstation layout and implemented automated quality verification",
    },
  },
  {
    id: "2",
    name: "Customer Support Automation",
    description: "AI-powered system to handle common customer inquiries",
    kind: "Technology",
    location: "Customer Service Department",
    mode: "Automated",
    status: "Testing",
    defaultSectionId: "sec-002",
    defaultSectionName: "Support",
    defaultSubSectionId: "sub-002",
    defaultSubSectionName: "Tier 1 Support",
    defaultEventId: "evt-002",
    defaultEventName: "Ticket Creation",
    content: "Implementation guide for the customer support automation system.",
    problem: "Long response times for common customer inquiries",
    title: "AI Customer Support Assistant",
    what: "Implementation of AI chatbot for first-line customer support",
    why: "To reduce response time and free up human agents for complex issues",
    where: "Customer support portal and mobile app",
    when: "Pilot launched in Q1 2024",
    how: "Using natural language processing and integration with knowledge base",
    email: "support.manager@example.com",
    solutionDetails: {
      title: "Customer Support AI Assistant",
      description: "AI-powered chatbot that handles common customer inquiries",
      rootCause: "High volume of repetitive inquiries overwhelming human agents",
      countermeasure: "Automated response system with escalation path to human agents",
    },
  },
  {
    id: "3",
    name: "Supply Chain Visibility",
    description: "Real-time tracking system for supply chain management",
    kind: "Logistics",
    location: "Global Operations",
    mode: "Real-time",
    status: "Active",
    defaultSectionId: "sec-003",
    defaultSectionName: "Logistics",
    defaultSubSectionId: "sub-003",
    defaultSubSectionName: "Inventory Management",
    defaultEventId: "evt-003",
    defaultEventName: "Shipment Tracking",
    content: "Technical documentation for the supply chain visibility solution.",
    problem: "Limited visibility into inventory and shipment status across global operations",
    title: "Global Supply Chain Tracker",
    what: "Implementation of real-time tracking and analytics for supply chain",
    why: "To improve inventory management and reduce shipping delays",
    where: "Global logistics network",
    when: "Rolled out globally in Q4 2023",
    how: "Using IoT sensors, blockchain for verification, and analytics dashboard",
    email: "logistics.director@example.com",
    solutionDetails: {
      title: "Supply Chain Visibility Platform",
      description: "End-to-end visibility solution for global supply chain",
      rootCause: "Siloed systems and manual tracking processes",
      countermeasure: "Integrated digital platform with real-time data synchronization",
    },
  },
]

export const solutionKinds = [
  "Process Improvement",
  "Technology",
  "Logistics",
  "Human Resources",
  "Financial",
  "Marketing",
  "Other",
]
export const solutionModes = ["Continuous", "Automated", "Real-time", "Scheduled", "Manual", "Hybrid"]
export const solutionStatuses = ["Active", "Testing", "Planned", "Completed", "Archived"]
