# name: Test Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-test-backend:
#     name: Backend CI
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: ./nest-service

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Generate Prisma client
#         run: npx prisma generate

#       - name: Lint
#         run: npm run lint

#       - name: Run unit tests
#         run: npm run test

#       - name: Run e2e tests
#         run: npm run test:e2e

#   build-and-test-frontend:
#     name: Frontend CI
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: ./helperly-app

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Lint
#         run: npm run lint

#       - name: Build frontend
#         run: npm run build
